server:
  port: 8761
spring:
  profiles:
    active: dev
  application:
    name: sparrow-eureka
management:
  security:
    enabled: false
eureka:
  server:
    eviction-interval-timer-in-ms: 20000
    enable-self-preservation: true