version: '2'

services:
  apollo-quick-start:
    image: apollo-quick-start
    container_name: apollo-quick-start
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8070:8070"
    links:
      - apollo-db

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./apollo/sql:/docker-entrypoint-initdb.d
    volumes_from:
      - apollo-dbdata

  apollo-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
      - /var/lib/mysql

  sparrow-admin:
    build: ./sparrow-admin/
    ports:
      - "8765:8765"
    expose:
      - 8765
    links:
      - apollo-quick-start

  sparrow-auth:
    build: ./sparrow-auth/
    ports:
      - "8763:8763"
    expose:
      - 8763
    links:
      - apollo-quick-start

  sparrow-biz-demo:
    build: ./sparrow-biz-demo/
    ports:
      - "8081:8081"
    expose:
      - 8081
    links:
      - apollo-quick-start
  sparrow-gateway:
    build: ./sparrow-gateway/
    ports:
      - "8762:8762"
    expose:
      - 8762
    links:
      - apollo-quick-start
