server:
  port: 8765
spring:
  application:
    name: sparrow-admin
  profiles:
    active: dev
  boot:
    admin:
      notify:
        mail:
          to: huenbin@foxmail.com
          from: enhinck@163.com
  mail:
    host: smtp.163.com
    username: enhinck@163.com
    password: HEBogg1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  security:
    enabled: false

security:
  user:
    name: admin
    password: 123456
  basic:
    enabled: false
sendPhones: 18968001908,18768439095
monitorServers: SC-AUTH,SC-USER,SC-GATEWAY

# 阿波罗配置
apollo:
  bootstrap:
    enabled: true
    namespaces: application,application.yml
app:
  id: sparrow