spring:
    application:
        name: sparrow-gateway
server:
    port: 8762 #启动端口
#
zuul:
#  zuul.servlet-path: /
  ignored-services: "*"
  sensitive-headers: "*"
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: REDIS #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 200
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url
  routes:
    auth:
      path: /auth/**
      serviceId: sparrow-auth
    biz:
      path: /biz/**
      serviceId: sparrow-biz-demo
    foos:
      path: /foos/**
      url: https://www.baidu.com/



gate:
  ignore:
    startWith: /**/*swagger-ui*/**,/**/swagger-resources/**,/**/api-docs*/**,/static**
    
